#!/bin/bash

# Initialize conda
echo "Initialize conda"
source "/srv/conda/etc/profile.d/conda.sh"

# Activate conda environment
echo "Activating conda environment"
conda activate /srv/conda/envs/notebook

# I don't do it earlier 'cause I don't want to mess with conda.sh
set -euo pipefail

# Clone repository
echo "Clone demo-notebook"
git clone --single-branch -b master https://github.com/bjorgve/vampyr-demo.git
echo "Cloning use-conda-package branch of robertodr/vampyr"
git clone --single-branch -b use-conda-package https://github.com/robertodr/vampyr.git

# Configure
echo "Configuring vampyr"
cd vampyr
./setup --type=debug
# Build
echo "Building vampyr"
cd build
make

## Test a little bit
#echo "Running smoke tests"
#(
#cd objdir || exit
#ctest -L smoke
#)
#
## Install
#echo "Installing Psi4"
#cmake --build objdir --target install

# Proper initialization of conda, maybe it sticks?
# conda init bash
