#!/bin/bash

set -euo pipefail

# Make available to Python
echo "Export PYTHONPATH"
export PYTHONPATH="${HOME}/Software/vampyr/build/lib${PYTHONPATH:+:$PYTHONPATH}"
echo "PYTHONPATH is now set to ${PYTHONPATH}"

exec "$@"
